{% set version = "2.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-leaflet.providers
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/leaflet.providers_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/leaflet.providers/leaflet.providers_{{ version }}.tar.gz
  sha256: c5ceeadc8088c9840a8249f0347501cdba0119be97219a01ea2050d1dd4a8666

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-htmltools
  run:
    - r-base
    - r-htmltools

test:
  commands:
    - $R -e "library('leaflet.providers')"           # [not win]
    - "\"%R%\" -e \"library('leaflet.providers')\""  # [win]

about:
  home: https://rstudio.github.io/leaflet.providers/
  dev_url: https://github.com/rstudio/leaflet.providers
  license: BSD_2_clause
  summary: Contains third-party map tile provider information from 'Leaflet.js', <https://github.com/leaflet-extras/leaflet-providers>, to be used with the 'leaflet' R package. Additionally, 'leaflet.providers' enables users to retrieve up-to-date provider information between package updates.
  license_family: BSD
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_2_clause'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
